-- 로봇 관절 도우미 테스트 데이터 (prisma/seed.ts와 같은 내용)
-- Supabase 대시보드 > SQL Editor에 전체를 붙여넣고 Run. 기존 데이터는 모두 지워진다.
BEGIN;

DELETE FROM "Progress";
UPDATE "User" SET "classId" = NULL, "teamId" = NULL;
DELETE FROM "Team";
DELETE FROM "Class";
DELETE FROM "User";

INSERT INTO "User" (id, email, name, role) VALUES ('teacher_1', 'teacher1@robotarm.test', '김선생', 'teacher');
INSERT INTO "Class" (id, "teacherId", name) VALUES ('class_1', 'teacher_1', '1학년 1반 로봇팔반');
INSERT INTO "Team" (id, "classId", name) VALUES ('team_1', 'class_1', '1모둠');
INSERT INTO "Team" (id, "classId", name) VALUES ('team_2', 'class_1', '2모둠');
INSERT INTO "Team" (id, "classId", name) VALUES ('team_3', 'class_1', '3모둠');
INSERT INTO "Team" (id, "classId", name) VALUES ('team_4', 'class_1', '4모둠');
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_1', 'student1@robotarm.test', '김민준', 'student', 'class_1', 'team_1');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_1', 'student_1', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_2', 'student_1', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_3', 'student_1', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_4', 'student_1', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_5', 'student_1', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_6', 'student_1', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_1_7', 'student_1', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_2', 'student2@robotarm.test', '이서연', 'student', 'class_1', 'team_1');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_1', 'student_2', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_2', 'student_2', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_3', 'student_2', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_4', 'student_2', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_5', 'student_2', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_6', 'student_2', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_2_7', 'student_2', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_3', 'student3@robotarm.test', '박도윤', 'student', 'class_1', 'team_2');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_1', 'student_3', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_2', 'student_3', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_3', 'student_3', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_4', 'student_3', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_5', 'student_3', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_6', 'student_3', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_3_7', 'student_3', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_4', 'student4@robotarm.test', '최지우', 'student', 'class_1', 'team_2');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_1', 'student_4', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_2', 'student_4', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_3', 'student_4', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_4', 'student_4', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_5', 'student_4', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_6', 'student_4', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_4_7', 'student_4', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_5', 'student5@robotarm.test', '정하은', 'student', 'class_1', 'team_3');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_1', 'student_5', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_2', 'student_5', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_3', 'student_5', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_4', 'student_5', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_5', 'student_5', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_6', 'student_5', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_5_7', 'student_5', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_6', 'student6@robotarm.test', '강시우', 'student', 'class_1', 'team_3');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_1', 'student_6', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_2', 'student_6', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_3', 'student_6', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_4', 'student_6', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_5', 'student_6', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_6', 'student_6', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_6_7', 'student_6', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_7', 'student7@robotarm.test', '조은우', 'student', 'class_1', 'team_4');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_1', 'student_7', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_2', 'student_7', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_3', 'student_7', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_4', 'student_7', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_5', 'student_7', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_6', 'student_7', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_7_7', 'student_7', 7, 'not_started', NOW());
INSERT INTO "User" (id, email, name, role, "classId", "teamId") VALUES ('student_8', 'student8@robotarm.test', '윤서아', 'student', 'class_1', 'team_4');
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_1', 'student_8', 1, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_2', 'student_8', 2, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_3', 'student_8', 3, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_4', 'student_8', 4, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_5', 'student_8', 5, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_6', 'student_8', 6, 'not_started', NOW());
INSERT INTO "Progress" (id, "userId", step, status, "updatedAt") VALUES ('progress_student_8_7', 'student_8', 7, 'not_started', NOW());

COMMIT;
